### ISSUE TITLE
num_workers causes train_vae.py to hang indefinitely

### ISSUE THREAD

**Issue by harubaru** [tgisaturday/dalle-lightning#11]
Hello! I've recently attempted to train a VAE on a TPU v3-8 VM and it hangs during validation. I've fixed it by setting ``args.num_workers`` to 0, but of course, it makes training much slower.
```
Traceback (most recent call last):██████████████████| 7/7 [02:08<00:00, 29.00s/it]
  File "train_vae.py", line 259, in <module>
    trainer.fit(model, datamodule=datamodule)
  File "/home/haru/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    self._run(model)
  File "/home/haru/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run
    self._dispatch()
  File "/home/haru/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1003, in _dispatch
    self.accelerator.start_training(self)
  File "/home/haru/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/haru/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py", line 267, in start_training
    xmp.spawn(self.new_process, **self.xmp_spawn_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 388, in spawn
    return torch.multiprocessing.start_processes(
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 99, in join
    ready = multiprocessing.connection.wait(
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
```

**Comment by tgisaturday** [comment]
@harubaru Yes, I'm facing the same issue and trying to figure out the cause. It doesn't happen every case. Can you tell me arguments you are using? This problem doesn't seems like vae specific but rather torch-xla or lightning.

**Comment by harubaru** [comment]
I am using default flags except for ``--use_tpus`` and ``--epochs 5`` to test it on real data.

**Comment by tgisaturday** [comment]
@harubaru Can you test it out with --fake_data? I've tried training with Imagenet21k and validation works okay for me. You can also use --debug flag for debugging efficienency.

**Comment by tgisaturday** [comment]
@harubaru It's a bit strange solution but setting num_workers to at least 16 solved the issue. Especially for Cloud TPU, try num_workers=48 which is number of cpus in each TPU machine. My run didn't hang for more than 5 epochs.

**Comment by harubaru** [comment]
@tgisaturday That is a strange solution indeed, but that seemed to have worked! Thanks!
