### ISSUE TITLE
Bad Iterator Type

### ISSUE THREAD

**Issue by afiaka87** [tgisaturday/dalle-lightning#8]
Just got this one trying to train on the VQGAN with GPUs again.
edit: seems to be occurring with the VQVAE2 as well.
```
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/content/lib/dalle-lightning/train_vae.py", line 22, in <module>
    from pl_bolts.callbacks import TensorboardGenerativeModelImageSampler
  File "/usr/local/lib/python3.7/dist-packages/pl_bolts/__init__.py", line 19, in <module>
    from pl_bolts import (  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pl_bolts/datamodules/__init__.py", line 5, in <module>
    from pl_bolts.datamodules.experience_source import DiscountedExperienceSource, ExperienceSource, ExperienceSourceDataset
  File "/usr/local/lib/python3.7/dist-packages/pl_bolts/datamodules/experience_source.py", line 24, in <module>
    class ExperienceSourceDataset(IterableDataset):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py", line 273, in __new__
    return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
  File "/usr/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py", line 371, in _dp_init_subclass
    ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable
```

**Comment by tgisaturday** [comment]
@afiaka87 Hmmm....that's strange. pl_bolts.callback is used to log image outputs but currently not working. I'm trying to find out the best way but please comment it out for now.

**Comment by tgisaturday** [comment]
@afiaka87 I removed pl_bolts image logger and added my custom one here: https://github.com/tgisaturday/dalle-lightning/blob/558af690c4fdb4be9336f5fa89f5fca0c2a4f101/pl_dalle/callbacks.py#L19

It runs on TPUs. Please test it out.

**Comment by afiaka87** [comment]
```
Traceback (most recent call last):
  File "/content/lib/dalle-lightning/train_vae.py", line 17, in <module>
    from pl_dalle.callbacks import VAEImageSampler
  File "/content/lib/dalle-lightning/pl_dalle/callbacks.py", line 8, in <module>
    from pl_bolts.utils import _TORCHVISION_AVAILABLE
  File "/usr/local/lib/python3.7/dist-packages/pl_bolts/__init__.py", line 19, in <module>
    from pl_bolts import (  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pl_bolts/datamodules/__init__.py", line 5, in <module>
    from pl_bolts.datamodules.experience_source import DiscountedExperienceSource, ExperienceSource, ExperienceSourceDataset
  File "/usr/local/lib/python3.7/dist-packages/pl_bolts/datamodules/experience_source.py", line 24, in <module>
    class ExperienceSourceDataset(IterableDataset):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py", line 273, in __new__
    return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
  File "/usr/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py", line 371, in _dp_init_subclass
    ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable
```

**Comment by tgisaturday** [comment]
@afiaka87 Are you using webdataset? I've also tested local dataset loader with A100 gpu and training started without any problem. Haven't tested with webdataset yet.

**Comment by afiaka87** [comment]
> @afiaka87 Are you using webdataset? I've also tested local dataset loader with A100 gpu and training started without any problem. Haven't tested with webdataset yet.

hmm I'll double check later today 👍

It happened using the regular data loader but I may have been on an old version by mistake.
